### ISSUE TITLE
Fleets not visible in Firefox 43 and IE 11

### ISSUE THREAD

**Issue by Systemdir** [janScheible/rising-empire#2]
The fleets are not visible when logged in with Firefox (43.0.4).
![no fleets](https://cloud.githubusercontent.com/assets/4005451/12880403/72028b78-ce40-11e5-8f4e-bd66faf8c441.PNG)
(left side chrome, right side firefox)

**Comment by janScheible** [comment]
IE 11 also has problems... seems that the fleets are Chrome exclusive... ;-(

**Comment by janScheible** [comment]
Thank you very much @Ootmann  df92bca fixed the problem for me in Firefox 56 but unfortunately not in IE 11.
